/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppEmojisIndexRouteImport } from './routes/_app/emojis/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppEmojisEmojiRouteImport } from './routes/_app/emojis/$emoji'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmojisIndexRoute = AppEmojisIndexRouteImport.update({
  id: '/emojis/',
  path: '/emojis/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppEmojisEmojiRoute = AppEmojisEmojiRouteImport.update({
  id: '/emojis/$emoji',
  path: '/emojis/$emoji',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/trends': typeof AppTrendsRoute
  '/emojis/$emoji': typeof AppEmojisEmojiRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/emojis/': typeof AppEmojisIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/trends': typeof AppTrendsRoute
  '/': typeof AppIndexRoute
  '/emojis/$emoji': typeof AppEmojisEmojiRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/emojis': typeof AppEmojisIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/trends': typeof AppTrendsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/emojis/$emoji': typeof AppEmojisEmojiRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/emojis/': typeof AppEmojisIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trends'
    | '/emojis/$emoji'
    | '/users/$userId'
    | '/emojis/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/trends'
    | '/'
    | '/emojis/$emoji'
    | '/users/$userId'
    | '/emojis'
    | '/users'
  id:
    | '__root__'
    | '/_app'
    | '/_app/trends'
    | '/_app/'
    | '/_app/emojis/$emoji'
    | '/_app/users/$userId'
    | '/_app/emojis/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emojis/': {
      id: '/_app/emojis/'
      path: '/emojis'
      fullPath: '/emojis/'
      preLoaderRoute: typeof AppEmojisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emojis/$emoji': {
      id: '/_app/emojis/$emoji'
      path: '/emojis/$emoji'
      fullPath: '/emojis/$emoji'
      preLoaderRoute: typeof AppEmojisEmojiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmojisEmojiRoute: typeof AppEmojisEmojiRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppEmojisIndexRoute: typeof AppEmojisIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmojisEmojiRoute: AppEmojisEmojiRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppEmojisIndexRoute: AppEmojisIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
