// Secrets configured via `wrangler secret put` — not in wrangler.jsonc.
// These augment the Env interface generated by `wrangler types`.
declare namespace Cloudflare {
  interface Env {
    SLACK_BOT_TOKEN: string;
    SLACK_SIGNING_SECRET: string;
    SITE_PASSWORD: string;
    TURNSTILE_SECRET_KEY: string;
    SESSION_TTL_HOURS: string;
  }
}
