/**
 * Print SQL that upserts the current custom Slack emoji set into `emoji_images`.
 *
 * Pipes to wrangler:
 *   bun scripts/sync-emojis.ts | bunx wrangler d1 execute DB --remote --config packages/worker/wrangler.jsonc --command -
 *
 * Or just inspect:
 *   bun scripts/sync-emojis.ts
 *
 * Env vars:
 *   SLACK_BOT_TOKEN  — required
 */

const MAX_RETRIES = 5;
const SQL_BATCH_SIZE = 500;

const SLACK_TOKEN = process.env.SLACK_BOT_TOKEN;
if (!SLACK_TOKEN) {
  console.error("SLACK_BOT_TOKEN is required");
  process.exit(1);
}

function esc(value: string): string {
  return value.replace(/'/g, "''");
}

function chunks<T>(arr: T[], size: number): T[][] {
  const result: T[][] = [];
  for (let i = 0; i < arr.length; i += size) {
    result.push(arr.slice(i, i + size));
  }
  return result;
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function slackApi<T>(
  method: string,
  params: Record<string, string> = {},
): Promise<T> {
  const url = new URL(`https://slack.com/api/${method}`);
  for (const [k, v] of Object.entries(params)) {
    url.searchParams.set(k, v);
  }

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${SLACK_TOKEN}` },
    });

    if (res.status === 429) {
      const retryAfter = Number(res.headers.get("Retry-After") ?? "5");
      console.error(
        `  Rate limited on ${method}, retrying in ${retryAfter}s (attempt ${attempt + 1}/${MAX_RETRIES})`,
      );
      await sleep(retryAfter * 1000);
      continue;
    }

    if (!res.ok) {
      throw new Error(`Slack API ${method} HTTP ${res.status}`);
    }
    const data = (await res.json()) as T & { ok: boolean; error?: string };
    if (!data.ok) {
      throw new Error(`Slack API ${method}: ${data.error}`);
    }
    return data;
  }

  throw new Error(
    `Slack API ${method}: rate limited after ${MAX_RETRIES} retries`,
  );
}

console.error("Fetching custom emoji list...");

type EmojiRow = { name: string; imageUrl: string };
const emojiRows: EmojiRow[] = [];

const res = await slackApi<{ emoji: Record<string, string> }>("emoji.list");
for (const [name, url] of Object.entries(res.emoji)) {
  if (url.startsWith("alias:")) {
    continue;
  }
  emojiRows.push({ name, imageUrl: url });
}
console.error(`  Fetched ${emojiRows.length} custom emojis`);

const lines: string[] = [];
lines.push(`-- Generated by sync-emojis.ts on ${new Date().toISOString()}`);
lines.push("");

for (const batch of chunks(emojiRows, SQL_BATCH_SIZE)) {
  lines.push(
    "INSERT OR REPLACE INTO emoji_images (name, image_url, updated_at) VALUES",
  );
  const values = batch.map(
    (e) => `  ('${esc(e.name)}', '${esc(e.imageUrl)}', datetime('now'))`,
  );
  lines.push(`${values.join(",\n")};`);
  lines.push("");
}

process.stdout.write(lines.join("\n"));
